### ISSUE TITLE
Better Instructions

### ISSUE THREAD

**Issue by DSigmund** [Heholord/FalconStats#13]
1. Is this hosted on npmjs.com? If not, add git clone command
2. Where should i clone this repo to?
3.  How do I install this to the motd? link the scripts?
4. How can i test if it works (without logging out and in again)?

Just some suggestions, really like the effort here :-)

**Comment by HermannBjorgvin** [comment]
1. No.
2. Your choice, maybe /etc/update-motd/
3. Move files and chmod +x
4. run-parts on the motd directory

**Comment by DSigmund** [comment]
Many Thanks for the answers! May i Suggest adding these to the README.md?
