### ISSUE TITLE
hddtemp throws an error (Debian 9): Unexpected token [

### ISSUE THREAD

**Issue by RlndVt** [Heholord/FalconStats#9]
```
let [name, temp] = match.slice(1);
    ^

SyntaxError: Unexpected token [
```

Don't have any experience with nodejs but it seems like you can't define two variables in one line, or at least not like this.

**Comment by HermannBjorgvin** [comment]
You need a newer version of nodejs probably. Sorry about that. If you really need it to be compatible with older versions of node I would recommend compiling the script with babel

**Comment by HermannBjorgvin** [comment]
You can try this new version written in bash by Darooke
https://github.com/darookee/FalconStats/tree/convert-to-bash/scripts
